apiVersion: v1
kind: Service
metadata:
    name: "kuberneetes28-4e18"
    labels:
        app: "kuberneetes28-4e18"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kuberneetes28-4e18"